channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=23.3.1
- pip:
  - mlflow==2.6.0
  - cloudpickle==2.2.1
  - importlib-metadata==6.0.0
  - numpy==1.23.5
  - psutil==5.9.0
  - scikit-learn==1.3.0
  - scipy==1.11.4
name: mlflow-env
